name: teachopencadd-c

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - jupyterlab
  - pandas=2.1.4
  - notebook=7
  - tqdm
  - pyarrow
  - ipywidgets=8
  - matplotlib=3.8
  - rdkit=2023.9
  - opencadd
  - pypdb=2
  - redo=2
  - nglview=3
  - requests-cache
  - bravado=11
  - matplotlib-venn
