environments:
  #- name: teachopencadd-a
    #file: environment_a.yml
    #notebooks:
      #- T001_query_chembl
  - name: teachopencadd-b
    file: environment_b.yml
    notebooks:
      - T002_compound_adme
      - T003_compound_unwanted_substructures
      - T004_compound_similarity
      - T005_compound_clustering
      - T006_compound_maximum_common_substructures
      - T007_compound_activity_machine_learning
      - T013_query_pubchem
  - name: teachopencadd-c
    file: environment_c.yml
    notebooks:
      - T008_query_pdb
      - T012_query_klifs
      - T014_binding_site_detection
  - name: teachopencadd-d
    file: environment_d.yml
    notebooks:
      - T009_compound_ensemble_pharmacophores
  - name: teachopencadd-e
    file: environment_e.yml
    notebooks:
      - T010_binding_site_comparison
